"""Constants shared across the Bone Merge Capture plugin."""

BONESTORE_INI_FILE_NAME = "BoneStore.ini"
CAPTURE_MANIFEST_FILE_NAME = "capture_manifest.json"
EXPORT_MANIFEST_FILE_NAME = "export_manifest.json"
HLSL_EXPORT_DIR_NAME = "hlsl"
BUFFER_EXPORT_DIR_NAME = "Buffer"
DEFAULT_PREVIOUS_ROW_OFFSET = 100000
LOCAL_PREVIOUS_ROW_OFFSET = 1024
GLOBAL_RESERVED_ROWS = 3
FLOAT_WEIGHT_EPSILON = 1e-8
BI4_MAX_BONE_INDEX = 255
BI4_MAX_BONE_COUNT = BI4_MAX_BONE_INDEX + 1
