"""BoneStore.ini generation helpers."""

from __future__ import annotations

import os
import re
import zlib

from ..constants import BONESTORE_INI_FILE_NAME, BUFFER_EXPORT_DIR_NAME, LOCAL_PREVIOUS_ROW_OFFSET
from .io import write_uint32_buffer
from .models import LocalPaletteRecord, PartRecord


_SAFE_NAMESPACE_RE = re.compile(r"[^0-9A-Za-z_]+")


def build_bonestore_namespace(output_directory: str) -> str:
    normalized_output_directory = os.path.abspath(output_directory)
    base_name = os.path.basename(normalized_output_directory.rstrip("\\/")) or "BoneStore"
    safe_base_name = _SAFE_NAMESPACE_RE.sub("_", base_name).strip("_") or "BoneStore"
    checksum = zlib.crc32(normalized_output_directory.lower().encode("utf-8")) & 0xFFFFFFFF
    return f"BMC\\{safe_base_name}_{checksum:08x}"


def build_bonestore_ini_content(
    part_records: list[PartRecord],
    local_palette_records: list[LocalPaletteRecord],
    namespace: str | None = None,
) -> str:
    unique_part_records = _deduplicate_part_records(part_records)
    effective_palette_records = _build_effective_palette_records(unique_part_records, local_palette_records)
    lines: list[str] = []
    if namespace:
        lines.append(f"namespace = {namespace}")
        lines.append("")
    lines.append("; Auto-generated by Bone Merge Capture")
    lines.append("; Stage 1: capture original per-IB palettes into the global bone buffer")
    lines.append("; Stage 2: gather the final exported chunk's required bones into a local small buffer")
    lines.append(";")
    lines.append("; IMPORTANT:")
    lines.append(";   ResourceBoneMeta_<ib>.y      = source/capture bone count for that original IB")
    lines.append(";   ResourceLocalPaletteMeta.x   = local palette bone count for one final exported chunk")
    lines.append(";   These are different concepts and should not be mixed.")
    lines.append("")
    lines.extend(_shader_override_sections(unique_part_records))
    lines.append("")
    lines.extend(_shared_resource_sections())
    lines.append("")
    lines.extend(_local_palette_sections(effective_palette_records))
    if effective_palette_records:
        lines.append("")
    palette_by_identity_key = {
        (record.ib_hash, record.match_index_count, record.chunk_index): record for record in effective_palette_records
    }
    for part_record in unique_part_records:
        local_palette_record = palette_by_identity_key[(part_record.ib_hash, part_record.match_index_count, 0)]
        lines.extend(_part_sections(part_record, local_palette_record))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_bonestore_ini(
    output_directory: str,
    part_records: list[PartRecord],
    local_palette_records: list[LocalPaletteRecord],
) -> str:
    os.makedirs(output_directory, exist_ok=True)
    ini_path = os.path.join(output_directory, BONESTORE_INI_FILE_NAME)
    namespace = build_bonestore_namespace(output_directory)
    materialized_palette_records = _materialize_local_palette_buffers(
        output_directory,
        part_records,
        local_palette_records,
    )
    with open(ini_path, "w", encoding="utf-8", newline="\n") as file_handle:
        file_handle.write(build_bonestore_ini_content(part_records, materialized_palette_records, namespace=namespace))
    return ini_path


def _deduplicate_part_records(part_records: list[PartRecord]) -> list[PartRecord]:
    unique_records: list[PartRecord] = []
    seen_keys: set[tuple[str, int]] = set()
    for part_record in sorted(part_records, key=lambda item: (int(item.draw_index), int(item.global_bone_base))):
        key = (part_record.ib_hash.lower(), int(part_record.match_index_count))
        if key in seen_keys:
            continue
        seen_keys.add(key)
        unique_records.append(part_record)
    return unique_records


def _shader_override_sections(part_records: list[PartRecord]) -> list[str]:
    lines: list[str] = []
    seen_hashes: set[str] = set()
    for part_record in part_records:
        vs_hash = part_record.vs_hash.lower()
        if vs_hash in seen_hashes:
            continue
        seen_hashes.add(vs_hash)
        lines.extend(
            [
                f"[ShaderOverrideBoneStoreVS_{vs_hash}]",
                f"hash = {vs_hash}",
                "filter_index = 200",
                "allow_duplicate_hash = overrule",
                "",
            ]
        )
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _shared_resource_sections() -> list[str]:
    return [
        "; -------------------------------------------------",
        "; Shared buffers",
        "; -------------------------------------------------",
        "[ResourceDumpedCB1_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceDumpedCB1_SRV]",
        "type = Buffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceFakeCB1_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceFakeCB1]",
        "type = Buffer",
        "stride = 16",
        "format = R32G32B32A32_UINT",
        "array = 4096",
        "",
        "[ResourceFakeT0_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 200000",
        "",
        "[ResourceFakeT0_SRV]",
        "type = StructuredBuffer",
        "stride = 16",
        "array = 200000",
        "",
        "[ResourceLocalFakeT0_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceLocalFakeT0_SRV]",
        "type = StructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "; -------------------------------------------------",
        "; Stage 1 shaders: extract -> store into global FakeT0",
        "; -------------------------------------------------",
        "[CustomShader_ExtractCB1]",
        "vs = hlsl\\extract_cb1_vs.hlsl",
        "ps = hlsl\\extract_cb1_ps.hlsl",
        "ps-u7 = ResourceDumpedCB1_UAV",
        "depth_enable = false",
        "blend = ADD SRC_ALPHA INV_SRC_ALPHA",
        "cull = none",
        "topology = point_list",
        "draw = 4096, 0",
        "ps-u7 = null",
        "ResourceDumpedCB1_SRV = copy ResourceDumpedCB1_UAV",
        "",
        "[CustomShader_RecordBones]",
        "cs = hlsl\\record_bones_dynamic_cs.hlsl",
        "cs-t0 = vs-t0",
        "cs-t1 = ResourceDumpedCB1_SRV",
        "; cs-t2 = ResourceBoneMeta_<ib>",
        "cs-u1 = ResourceFakeT0_UAV",
        "dispatch = 64, 1, 1",
        "cs-u1 = null",
        "cs-t0 = null",
        "cs-t1 = null",
        "cs-t2 = null",
        "ResourceFakeT0_SRV = copy ResourceFakeT0_UAV",
        "",
        "[CustomShader_GatherBones]",
        "cs = hlsl\\gather_bones_cs.hlsl",
        "cs-t0 = ResourceFakeT0_SRV",
        "cs-u1 = ResourceLocalFakeT0_UAV",
        "dispatch = 64, 1, 1",
        "cs-u1 = null",
        "cs-t0 = null",
        "cs-t2 = null",
        "cs-t3 = null",
        "ResourceLocalFakeT0_SRV = copy ResourceLocalFakeT0_UAV",
        "",
        "[CustomShader_RedirectCB1]",
        "cs = hlsl\\redirect_cb1_cs.hlsl",
        "cs-t0 = ResourceDumpedCB1_SRV",
        "; This is the only RedirectCB1 path now: it redirects cb1[5].x/.y",
        "; to the shared local gathered palette buffer, not the global buffer.",
        "cs-u0 = ResourceFakeCB1_UAV",
        "dispatch = 4, 1, 1",
        "cs-u0 = null",
        "cs-t0 = null",
        "ResourceFakeCB1 = copy ResourceFakeCB1_UAV",
        "",
        "; Local palette resources are generated per IB below.",
        "; ResourceBoneMeta_<ib>.y stores the original source IB bone count used by RecordBones.",
        "; ResourceLocalPaletteMeta_<ib>_<count>_0.x stores the local palette bone count used by GatherBones.",
        "; RedirectCB1 only needs the current consuming draw's cb1 as input; it rewrites",
        "; cb1[5].x/.y to point at the shared local palette buffer.",
    ]


def _local_palette_sections(local_palette_records: list[LocalPaletteRecord]) -> list[str]:
    if not local_palette_records:
        return []

    lines: list[str] = [
        "; -------------------------------------------------",
        "; Local palettes generated during export preparation",
        "; -------------------------------------------------",
    ]
    seen_suffixes: set[str] = set()
    for local_palette_record in local_palette_records:
        if local_palette_record.resource_suffix in seen_suffixes:
            continue
        seen_suffixes.add(local_palette_record.resource_suffix)
        lines.extend(
            [
                f"[ResourceLocalPalette_{local_palette_record.resource_suffix}]",
                "type = Buffer",
                "format = R32_UINT",
                _local_palette_data_line(local_palette_record),
                "",
                f"[ResourceLocalPaletteMeta_{local_palette_record.resource_suffix}]",
                "type = Buffer",
                "format = R32_FLOAT",
                f"data = R32_FLOAT {float(local_palette_record.local_bone_count):.1f}",
                "",
            ]
        )
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _build_effective_palette_records(
    part_records: list[PartRecord],
    local_palette_records: list[LocalPaletteRecord],
) -> list[LocalPaletteRecord]:
    records_by_identity = {
        (record.ib_hash.lower(), int(record.match_index_count), int(record.chunk_index)): record
        for record in local_palette_records
    }

    effective_records: list[LocalPaletteRecord] = []
    used_keys: set[tuple[str, int, int]] = set()
    for part_record in part_records:
        key = (part_record.ib_hash.lower(), int(part_record.match_index_count), 0)
        record = records_by_identity.get(key)
        if record is None:
            record = _default_local_palette_record(part_record)
        effective_records.append(record)
        used_keys.add(key)

    for key, record in sorted(records_by_identity.items(), key=lambda item: item[0]):
        if key in used_keys:
            continue
        effective_records.append(record)
    return effective_records


def _default_local_palette_record(part_record: PartRecord) -> LocalPaletteRecord:
    hash_value = part_record.ib_hash.lower()
    match_index_count = int(part_record.match_index_count)
    palette_values = tuple(
        range(int(part_record.global_bone_base), int(part_record.global_bone_base) + int(part_record.bone_count))
    )
    return LocalPaletteRecord(
        object_name=part_record.object_name,
        ib_hash=hash_value,
        match_index_count=match_index_count,
        chunk_index=0,
        local_bone_count=len(palette_values),
        palette_values=palette_values,
        file_name=f"{hash_value}-{match_index_count}-0-Palette.buf",
        file_path="",
        resource_suffix=f"{hash_value}_{match_index_count}_0",
    )


def _local_palette_data_line(local_palette_record: LocalPaletteRecord) -> str:
    return f"filename = Buffer/{local_palette_record.file_name}"


def _materialize_local_palette_buffers(
    output_directory: str,
    part_records: list[PartRecord],
    local_palette_records: list[LocalPaletteRecord],
) -> list[LocalPaletteRecord]:
    buffer_directory = os.path.join(output_directory, BUFFER_EXPORT_DIR_NAME)
    os.makedirs(buffer_directory, exist_ok=True)
    unique_part_records = _deduplicate_part_records(part_records)

    materialized_records: list[LocalPaletteRecord] = []
    for record in _build_effective_palette_records(unique_part_records, local_palette_records):
        file_name = f"{record.ib_hash.lower()}-{int(record.match_index_count)}-{int(record.chunk_index)}-Palette.buf"
        file_path = os.path.join(buffer_directory, file_name)
        write_uint32_buffer(file_path, record.palette_values)
        materialized_records.append(
            LocalPaletteRecord(
                object_name=record.object_name,
                ib_hash=record.ib_hash.lower(),
                match_index_count=int(record.match_index_count),
                chunk_index=int(record.chunk_index),
                local_bone_count=int(record.local_bone_count),
                palette_values=tuple(int(value) for value in record.palette_values),
                file_name=file_name,
                file_path=file_path,
                resource_suffix=record.resource_suffix,
            )
        )
    return materialized_records


def _part_sections(part_record: PartRecord, local_palette_record: LocalPaletteRecord | None) -> list[str]:
    hash_value = part_record.ib_hash.lower()
    if _is_default_part_palette(part_record, local_palette_record):
        palette_comment = (
            "; Stage 2 palette: original game local order. "
            "No exported chunk overrides this IB, so local i maps to its original captured bone."
        )
    else:
        palette_comment = (
            f"; Stage 2 palette: exported chunk {local_palette_record.resource_suffix} "
            f"({local_palette_record.local_bone_count} local bones)"
        )
    lines = [
        f"[ResourceBoneMeta_{hash_value}]",
        "type = Buffer",
        "format = R32_FLOAT",
        f"data = R32_FLOAT {float(part_record.global_bone_base):.1f} {float(part_record.bone_count):.1f}",
        "",
    ]

    lines.extend(
        [
        f"[TextureOverride_IB_{hash_value}_merge]",
        f"hash = {hash_value}",
        f"match_index_count = {part_record.match_index_count}",
        "match_priority = -500",
        "if vs == 200",
        "  run = CustomShader_ExtractCB1",
        f"  cs-t2 = ResourceBoneMeta_{hash_value}",
        "  run = CustomShader_RecordBones",
        "endif",
        ]
    )
    lines.extend(
        [
            palette_comment,
            "run = CustomShader_ExtractCB1",
            f"cs-t2 = ResourceLocalPalette_{local_palette_record.resource_suffix}",
            f"cs-t3 = ResourceLocalPaletteMeta_{local_palette_record.resource_suffix}",
            "run = CustomShader_GatherBones",
            "vs-t0 = ResourceLocalFakeT0_SRV",
            "run = CustomShader_RedirectCB1",
            "vs-cb1 = ResourceFakeCB1",
        ]
    )
    return lines


def _is_default_part_palette(part_record: PartRecord, local_palette_record: LocalPaletteRecord) -> bool:
    expected_values = tuple(
        range(int(part_record.global_bone_base), int(part_record.global_bone_base) + int(part_record.bone_count))
    )
    return (
        local_palette_record.ib_hash.lower() == part_record.ib_hash.lower()
        and int(local_palette_record.match_index_count) == int(part_record.match_index_count)
        and int(local_palette_record.chunk_index) == 0
        and tuple(int(value) for value in local_palette_record.palette_values) == expected_values
    )
