"""BoneStore runtime INI and static-buffer generation."""

from __future__ import annotations

import os
import re
import zlib

from ..constants import BONESTORE_INI_FILE_NAME, BUFFER_EXPORT_DIR_NAME
from .io import ensure_directory, write_uint32_buffer
from .models import LocalPaletteRecord


_SAFE_NAMESPACE_RE = re.compile(r"[^0-9A-Za-z_]+")
_SAFE_SUFFIX_RE = re.compile(r"[^0-9A-Za-z_]+")

_CAPTURE_META_FILE = "CaptureMeta.buf"
_CAPTURE_LOCAL_INDICES_FILE = "CaptureLocalIndices.buf"
_LOD_CAPTURE_META_FILE = "LodCaptureMeta.buf"
_LOD_CAPTURE_PAIRS_FILE = "LodCapturePairs.buf"


def build_bonestore_namespace(output_directory: str) -> str:
    normalized_output_directory = os.path.abspath(output_directory)
    base_name = os.path.basename(normalized_output_directory.rstrip("\\/")) or "BoneStore"
    safe_base_name = _SAFE_NAMESPACE_RE.sub("_", base_name).strip("_") or "BoneStore"
    checksum = zlib.crc32(normalized_output_directory.lower().encode("utf-8")) & 0xFFFFFFFF
    return f"BMC\\{safe_base_name}_{checksum:08x}"


def materialize_bonestore_runtime(
    output_directory: str,
    capture_manifest: dict,
    local_palette_records: list[LocalPaletteRecord],
) -> dict:
    """Write static runtime buffers and return the normalized runtime plan."""

    normalized_output_dir = ensure_directory(output_directory)
    buffer_dir = ensure_directory(os.path.join(normalized_output_dir, BUFFER_EXPORT_DIR_NAME))

    capture_records, capture_meta, capture_local_indices = _build_capture_tables(capture_manifest)
    lod_records, lod_meta, lod_pairs = _build_lod_capture_tables(capture_manifest)
    palette_records = _normalize_palette_records(normalized_output_dir, local_palette_records)
    _validate_palette_globals(capture_manifest, palette_records)

    capture_meta_path = write_uint32_buffer(
        os.path.join(buffer_dir, _CAPTURE_META_FILE),
        capture_meta or [0, 0, 0, 0],
    )
    capture_indices_path = write_uint32_buffer(
        os.path.join(buffer_dir, _CAPTURE_LOCAL_INDICES_FILE),
        capture_local_indices or [0],
    )
    lod_meta_path = write_uint32_buffer(
        os.path.join(buffer_dir, _LOD_CAPTURE_META_FILE),
        lod_meta or [0, 0, 0, 0],
    )
    lod_pairs_path = write_uint32_buffer(
        os.path.join(buffer_dir, _LOD_CAPTURE_PAIRS_FILE),
        lod_pairs or [0, 0],
    )

    return {
        "schema_version": 2,
        "namespace": build_bonestore_namespace(normalized_output_dir),
        "global_bone_count": _global_bone_count(capture_manifest),
        "shadow_vs_hashes": _runtime_shadow_vs_hashes(capture_manifest),
        "capture_records": capture_records,
        "lod_capture_records": lod_records,
        "palettes": palette_records,
        "buffers": {
            "capture_meta": _resource_file_payload(capture_meta_path, normalized_output_dir, len(capture_meta or [0, 0, 0, 0])),
            "capture_local_indices": _resource_file_payload(capture_indices_path, normalized_output_dir, len(capture_local_indices or [0])),
            "lod_capture_meta": _resource_file_payload(lod_meta_path, normalized_output_dir, len(lod_meta or [0, 0, 0, 0])),
            "lod_capture_pairs": _resource_file_payload(lod_pairs_path, normalized_output_dir, len(lod_pairs or [0, 0])),
        },
    }


def write_bonestore_ini(output_directory: str, runtime_plan: dict) -> str:
    os.makedirs(output_directory, exist_ok=True)
    ini_path = os.path.join(output_directory, BONESTORE_INI_FILE_NAME)
    with open(ini_path, "w", encoding="utf-8", newline="\n") as file_handle:
        file_handle.write(build_bonestore_ini_content(runtime_plan))
    return ini_path


def build_bonestore_ini_content(runtime_plan: dict) -> str:
    lines: list[str] = []
    namespace = str(runtime_plan.get("namespace", "") or "")
    if namespace:
        lines.append(f"namespace = {namespace}")
        lines.append("")

    lines.extend(
        [
            "; Auto-generated by Bone Merge Capture",
            "; Runtime schema v2:",
            ";   main capture: record index -> CaptureMeta + CaptureLocalIndices",
            ";   LOD capture:  record index -> LodCaptureMeta + LodCapturePairs",
            ";   consume:      exported local palette -> canonical global BoneStore pool",
            "",
        ]
    )
    lines.extend(_shader_override_sections(runtime_plan))
    if lines and lines[-1] != "":
        lines.append("")
    lines.extend(_resource_sections(runtime_plan))
    lines.append("")
    lines.extend(_custom_shader_sections())
    lines.append("")
    lines.extend(_local_palette_sections(runtime_plan))
    if runtime_plan.get("palettes"):
        lines.append("")
    lines.extend(_capture_override_sections(runtime_plan))
    return "\n".join(lines).rstrip() + "\n"


def _build_capture_tables(capture_manifest: dict) -> tuple[list[dict], list[int], list[int]]:
    records: list[dict] = []
    capture_meta: list[int] = []
    capture_local_indices: list[int] = []

    for pool_record in capture_manifest.get("bone_pool_order", []) or []:
        if not bool(pool_record.get("bone_capture_available", pool_record.get("shadow_capture_ready", False))):
            continue
        used_indices = _used_local_indices(pool_record)
        if not used_indices:
            continue

        record_index = len(records)
        local_index_base = len(capture_local_indices)
        capture_local_indices.extend(used_indices)
        capture_store_base = int(pool_record.get("capture_store_base", pool_record.get("global_bone_base", 0)) or 0)
        capture_meta.extend([capture_store_base, len(used_indices), local_index_base, 0])

        records.append(
            {
                "record_index": record_index,
                "ib_hash": str(pool_record.get("ib_hash", "") or "").lower(),
                "match_first_index": int(pool_record.get("match_first_index", 0) or 0),
                "match_index_count": int(pool_record.get("match_index_count", 0) or 0),
                "capture_store_base": capture_store_base,
                "local_bone_count": len(used_indices),
                "source_local_indices": list(used_indices),
                "local_index_base": local_index_base,
                "dispatch_rows": len(used_indices) * 3,
            }
        )

    return records, capture_meta, capture_local_indices


def _build_lod_capture_tables(capture_manifest: dict) -> tuple[list[dict], list[int], list[int]]:
    records: list[dict] = []
    lod_meta: list[int] = []
    lod_pairs: list[int] = []

    for lod_record in capture_manifest.get("lod_capture_records", []) or []:
        raw_pairs = list(lod_record.get("scatter_pairs", []) or [])
        pairs = [
            (
                int(pair.get("lod_local_bone", -1)),
                int(pair.get("canonical_global_bone", -1)),
            )
            for pair in raw_pairs
            if int(pair.get("lod_local_bone", -1)) >= 0 and int(pair.get("canonical_global_bone", -1)) >= 0
        ]
        if not pairs:
            continue

        record_index = len(records)
        pair_base = len(lod_pairs) // 2
        for lod_local_bone, canonical_global_bone in pairs:
            lod_pairs.extend([lod_local_bone, canonical_global_bone])
        lod_meta.extend([pair_base, len(pairs), int(lod_record.get("lod_local_bone_count", 0) or 0), 0])
        records.append(
            {
                "record_index": record_index,
                "lod_record_key": str(lod_record.get("lod_record_key", "") or ""),
                "ib_hash": str(lod_record.get("lod_ib_hash", "") or "").lower(),
                "match_first_index": int(lod_record.get("lod_match_first_index", 0) or 0),
                "match_index_count": int(lod_record.get("lod_match_index_count", 0) or 0),
                "pair_base": pair_base,
                "pair_count": len(pairs),
                "dispatch_rows": len(pairs) * 3,
            }
        )

    return records, lod_meta, lod_pairs


def _normalize_palette_records(output_directory: str, local_palette_records: list[LocalPaletteRecord]) -> list[dict]:
    normalized_records: list[dict] = []
    seen_suffixes: set[str] = set()
    buffer_dir = ensure_directory(os.path.join(output_directory, BUFFER_EXPORT_DIR_NAME))
    for record in local_palette_records:
        suffix = _safe_suffix(record.resource_suffix or f"{record.ib_hash}_{record.match_index_count}_{record.chunk_index}")
        if suffix in seen_suffixes:
            continue
        seen_suffixes.add(suffix)
        palette_values = tuple(int(value) for value in record.palette_values)
        file_name = record.file_name or f"{suffix}-Palette.buf"
        file_path = record.file_path or os.path.join(buffer_dir, file_name)
        if not os.path.exists(file_path):
            write_uint32_buffer(file_path, palette_values)
        normalized_records.append(
            {
                "object_name": str(record.object_name),
                "ib_hash": str(record.ib_hash).lower(),
                "match_index_count": int(record.match_index_count),
                "chunk_index": int(record.chunk_index),
                "local_bone_count": int(record.local_bone_count),
                "palette_values": list(palette_values),
                "file_name": file_name,
                "file_path": file_path,
                "resource_suffix": suffix,
                "variant_id": str(record.variant_id or ""),
                "filename": _resource_filename(file_path, output_directory),
            }
        )
    return normalized_records


def _validate_palette_globals(capture_manifest: dict, palette_records: list[dict]) -> None:
    unavailable = _capture_unavailable_global_bones(capture_manifest)
    if not unavailable:
        return

    errors: list[str] = []
    for palette_record in palette_records:
        used = sorted(unavailable.intersection(int(value) for value in palette_record.get("palette_values", []) or []))
        if not used:
            continue
        errors.append(
            f"{palette_record.get('resource_suffix')}: uses capture-unavailable global bone(s) "
            + ", ".join(str(value) for value in used[:12])
        )
    if errors:
        raise ValueError(
            "Export uses global bones that cannot be captured in the main shadow stage. "
            "Move those weights to captured globals or keep that source IB unmodified. "
            + " | ".join(errors[:3])
        )


def _capture_unavailable_global_bones(capture_manifest: dict) -> set[int]:
    unavailable: set[int] = set()
    for pool_record in capture_manifest.get("bone_pool_order", []) or []:
        if bool(pool_record.get("bone_capture_available", pool_record.get("shadow_capture_ready", False))):
            continue
        base = int(pool_record.get("global_bone_base", 0) or 0)
        count = int(pool_record.get("local_bone_count", 0) or 0)
        unavailable.update(range(base, base + max(0, count)))
    return unavailable


def _shader_override_sections(runtime_plan: dict) -> list[str]:
    lines: list[str] = []
    for vs_hash in runtime_plan.get("shadow_vs_hashes", []) or []:
        safe_hash = str(vs_hash).lower()
        if not safe_hash:
            continue
        lines.extend(
            [
                f"[ShaderOverrideBoneStoreVS_{safe_hash}]",
                f"hash = {safe_hash}",
                "filter_index = 200",
                "allow_duplicate_hash = overrule",
                "",
            ]
        )
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _resource_sections(runtime_plan: dict) -> list[str]:
    buffers = dict(runtime_plan.get("buffers", {}) or {})
    return [
        "; -------------------------------------------------",
        "; Static capture tables",
        "; -------------------------------------------------",
        *_buffer_resource("ResourceCaptureMeta", buffers.get("capture_meta", {})),
        "",
        *_buffer_resource("ResourceCaptureLocalIndices", buffers.get("capture_local_indices", {})),
        "",
        *_buffer_resource("ResourceLodCaptureMeta", buffers.get("lod_capture_meta", {})),
        "",
        *_buffer_resource("ResourceLodCapturePairs", buffers.get("lod_capture_pairs", {})),
        "",
        "; -------------------------------------------------",
        "; Shared runtime buffers",
        "; -------------------------------------------------",
        "[ResourceDumpedCB1_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceDumpedCB1_SRV]",
        "type = Buffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceFakeCB1_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceFakeCB1]",
        "type = Buffer",
        "stride = 16",
        "format = R32G32B32A32_UINT",
        "array = 4096",
        "",
        "[ResourceFakeT0_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 200000",
        "",
        "[ResourceFakeT0_SRV]",
        "type = StructuredBuffer",
        "stride = 16",
        "array = 200000",
        "",
        "[ResourceLocalFakeT0_UAV]",
        "type = RWStructuredBuffer",
        "stride = 16",
        "array = 4096",
        "",
        "[ResourceLocalFakeT0_SRV]",
        "type = StructuredBuffer",
        "stride = 16",
        "array = 4096",
    ]


def _custom_shader_sections() -> list[str]:
    return [
        "; -------------------------------------------------",
        "; Shaders",
        "; -------------------------------------------------",
        "[CustomShader_ExtractCB1]",
        "vs = hlsl\\extract_cb1_vs.hlsl",
        "ps = hlsl\\extract_cb1_ps.hlsl",
        "ps-u7 = ResourceDumpedCB1_UAV",
        "depth_enable = false",
        "blend = ADD SRC_ALPHA INV_SRC_ALPHA",
        "cull = none",
        "topology = point_list",
        "draw = 4096, 0",
        "ps-u7 = null",
        "ResourceDumpedCB1_SRV = copy ResourceDumpedCB1_UAV",
        "",
        "[CustomShader_RecordBones]",
        "cs = hlsl\\record_bones_dynamic_cs.hlsl",
        "cs-t0 = vs-t0",
        "cs-t1 = ResourceDumpedCB1_SRV",
        "cs-t2 = ResourceCaptureMeta",
        "cs-t3 = ResourceCaptureLocalIndices",
        "cs-u1 = ResourceFakeT0_UAV",
        "dispatch = 64, 1, 1",
        "cs-u1 = null",
        "cs-t0 = null",
        "cs-t1 = null",
        "cs-t2 = null",
        "cs-t3 = null",
        "",
        "[CustomShader_RecordBonesScatter]",
        "cs = hlsl\\record_bones_scatter_cs.hlsl",
        "cs-t0 = vs-t0",
        "cs-t1 = ResourceDumpedCB1_SRV",
        "cs-t2 = ResourceLodCaptureMeta",
        "cs-t3 = ResourceLodCapturePairs",
        "cs-u1 = ResourceFakeT0_UAV",
        "dispatch = 64, 1, 1",
        "cs-u1 = null",
        "cs-t0 = null",
        "cs-t1 = null",
        "cs-t2 = null",
        "cs-t3 = null",
        "",
        "[CustomShader_GatherBones]",
        "cs = hlsl\\gather_bones_cs.hlsl",
        "cs-t0 = ResourceFakeT0_SRV",
        "cs-u1 = ResourceLocalFakeT0_UAV",
        "dispatch = 64, 1, 1",
        "cs-u1 = null",
        "cs-t0 = null",
        "cs-t2 = null",
        "ResourceLocalFakeT0_SRV = copy ResourceLocalFakeT0_UAV",
        "",
        "[CustomShader_RedirectCB1]",
        "cs = hlsl\\redirect_cb1_cs.hlsl",
        "cs-t0 = ResourceDumpedCB1_SRV",
        "cs-u0 = ResourceFakeCB1_UAV",
        "dispatch = 4, 1, 1",
        "cs-u0 = null",
        "cs-t0 = null",
        "ResourceFakeCB1 = copy ResourceFakeCB1_UAV",
    ]


def _local_palette_sections(runtime_plan: dict) -> list[str]:
    palette_records = list(runtime_plan.get("palettes", []) or [])
    if not palette_records:
        return []

    lines: list[str] = [
        "; -------------------------------------------------",
        "; Export chunk palettes and consume command lists",
        "; -------------------------------------------------",
    ]
    for record in palette_records:
        suffix = str(record.get("resource_suffix", "") or "")
        lines.extend(
            [
                f"[ResourceLocalPalette_{suffix}]",
                "type = Buffer",
                "format = R32_UINT",
                f"filename = {record.get('filename')}",
                "",
                f"[CommandList_UsePalette_{suffix}]",
                "; Call this before drawing the exported chunk that owns this Palette.buf.",
                "run = CustomShader_ExtractCB1",
                f"x101 = {int(record.get('local_bone_count', 0) or 0)}",
                f"cs-t2 = ResourceLocalPalette_{suffix}",
                "run = CustomShader_GatherBones",
                "vs-t0 = ResourceLocalFakeT0_SRV",
                "run = CustomShader_RedirectCB1",
                "vs-cb1 = ResourceFakeCB1",
                "",
            ]
        )
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _capture_override_sections(runtime_plan: dict) -> list[str]:
    capture_by_key: dict[tuple[str, int, int], dict[str, list[int]]] = {}
    for record in runtime_plan.get("capture_records", []) or []:
        key = _override_key(record)
        capture_by_key.setdefault(key, {"main": [], "lod": []})["main"].append(int(record["record_index"]))
    for record in runtime_plan.get("lod_capture_records", []) or []:
        key = _override_key(record)
        capture_by_key.setdefault(key, {"main": [], "lod": []})["lod"].append(int(record["record_index"]))

    if not capture_by_key:
        return []

    lines: list[str] = [
        "; -------------------------------------------------",
        "; Capture TextureOverrides",
        "; -------------------------------------------------",
    ]
    for key, grouped_records in sorted(capture_by_key.items(), key=lambda item: item[0]):
        ib_hash, match_first_index, match_index_count = key
        suffix = _safe_suffix(f"{ib_hash}_{match_index_count}_{match_first_index}")
        lines.extend(
            [
                f"[TextureOverride_BMC_Capture_{suffix}]",
                f"hash = {ib_hash}",
                f"match_first_index = {match_first_index}",
                f"match_index_count = {match_index_count}",
                "match_priority = -500",
                "if vs == 200",
                "  run = CustomShader_ExtractCB1",
            ]
        )
        for record_index in grouped_records.get("main", []):
            lines.extend(
                [
                    f"  x100 = {record_index}",
                    "  run = CustomShader_RecordBones",
                ]
            )
        for record_index in grouped_records.get("lod", []):
            lines.extend(
                [
                    f"  x100 = {record_index}",
                    "  run = CustomShader_RecordBonesScatter",
                ]
            )
        lines.extend(
            [
                "  ResourceFakeT0_SRV = copy ResourceFakeT0_UAV",
                "endif",
                "",
            ]
        )
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _buffer_resource(name: str, payload: dict) -> list[str]:
    return [
        f"[{name}]",
        "type = Buffer",
        "format = R32_UINT",
        f"filename = {payload.get('filename', '')}",
    ]


def _resource_file_payload(path: str, output_directory: str, count: int) -> dict:
    return {
        "file_name": os.path.basename(path),
        "file_path": path,
        "filename": _resource_filename(path, output_directory),
        "uint_count": int(count),
    }


def _resource_filename(path: str, output_directory: str) -> str:
    try:
        relpath = os.path.relpath(path, output_directory)
    except ValueError:
        relpath = path
    return relpath.replace("\\", "/")


def _runtime_shadow_vs_hashes(capture_manifest: dict) -> list[str]:
    hashes: list[str] = []

    def add_many(values) -> None:
        for value in values or []:
            normalized = str(value or "").strip().lower()
            if normalized and normalized not in hashes:
                hashes.append(normalized)

    shadow_stage = dict(capture_manifest.get("shadow_stage", {}) or {})
    add_many(shadow_stage.get("shadow_vs_hashes", []))
    add_many([shadow_stage.get("normal_vs_hash", ""), shadow_stage.get("transparent_vs_hash", "")])

    lod_snapshot = dict(capture_manifest.get("lod_manifest_snapshot", {}) or {})
    lod_shadow_stage = dict(lod_snapshot.get("shadow_stage", {}) or {})
    add_many(lod_shadow_stage.get("shadow_vs_hashes", []))
    add_many([lod_shadow_stage.get("normal_vs_hash", ""), lod_shadow_stage.get("transparent_vs_hash", "")])
    return hashes


def _global_bone_count(capture_manifest: dict) -> int:
    count = 0
    for record in capture_manifest.get("bone_pool_order", []) or []:
        base = int(record.get("global_bone_base", 0) or 0)
        local_count = int(record.get("local_bone_count", 0) or 0)
        count = max(count, base + max(0, local_count))
    return count


def _used_local_indices(pool_record: dict) -> list[int]:
    raw_indices = pool_record.get("used_local_bone_indices", [])
    if raw_indices:
        return sorted({int(value) for value in raw_indices if int(value) >= 0})
    count = int(pool_record.get("local_bone_count", 0) or 0)
    return list(range(max(0, count)))


def _override_key(record: dict) -> tuple[str, int, int]:
    return (
        str(record.get("ib_hash", "") or "").lower(),
        int(record.get("match_first_index", 0) or 0),
        int(record.get("match_index_count", 0) or 0),
    )


def _safe_suffix(value: str) -> str:
    return _SAFE_SUFFIX_RE.sub("_", str(value)).strip("_") or "resource"
