"""Independent layout-faithful Simple Override export adapter."""

from __future__ import annotations

import os
from dataclasses import dataclass

from ..constants import BONESTORE_INI_FILE_NAME
from . import ini_export as runtime_ini
from .export_names import ini_filename_from_collection_name
from .io import ensure_directory
from .toggle_draw_sets import normalize_toggle_draw_sets


@dataclass(frozen=True)
class SimpleOverrideAdapter:
    """Materialize geometry-only overrides without BoneStore runtime state."""

    def materialize(
        self,
        output_directory: str,
        geometry_records: list[dict] | None = None,
        texture_mark_payload: dict | None = None,
        toggle_draw_sets: list[dict] | None = None,
    ) -> dict:
        normalized_output_dir = ensure_directory(output_directory)
        geometry_payloads = runtime_ini._normalize_geometry_records(normalized_output_dir, geometry_records or [])
        texture_records, texture_warnings = runtime_ini._materialize_texture_records(
            normalized_output_dir,
            texture_mark_payload or {},
        )
        return {
            "schema_version": 1,
            "mode": "simple_override",
            "adapter": "layout_faithful_v1",
            "namespace": "",
            "geometry": geometry_payloads,
            "textures": texture_records,
            "toggle_draw_sets": normalize_toggle_draw_sets(toggle_draw_sets or []),
            "texture_warnings": texture_warnings,
        }

    def build_ini_content(self, runtime_plan: dict) -> str:
        lines: list[str] = [
            "; Auto-generated by Bone Merge Capture",
            "; Simple Override Adapter: layout-faithful geometry and textures only",
            "",
        ]
        lines.extend(runtime_ini._geometry_resource_sections(runtime_plan))
        if lines and lines[-1] != "":
            lines.append("")
        lines.extend(runtime_ini._texture_resource_sections(runtime_plan))
        if runtime_plan.get("textures"):
            if lines and lines[-1] != "":
                lines.append("")
            lines.extend(runtime_ini._texture_hash_override_sections(runtime_plan))
            if lines and lines[-1] != "":
                lines.append("")
        lines.extend(_simple_texture_override_sections(runtime_plan))
        while lines and lines[-1] == "":
            lines.pop()
        return "\n".join(lines) + "\n"

    def write_ini(
        self,
        output_directory: str,
        runtime_plan: dict,
        *,
        ini_file_name: str | None = None,
    ) -> str:
        os.makedirs(output_directory, exist_ok=True)
        file_name = ini_filename_from_collection_name(
            ini_file_name or runtime_plan.get("ini_file_name", "") or BONESTORE_INI_FILE_NAME
        )
        ini_path = os.path.join(output_directory, file_name)
        with open(ini_path, "w", encoding="utf-8", newline="\n") as file_handle:
            file_handle.write(self.build_ini_content(runtime_plan))
        return ini_path


DEFAULT_SIMPLE_OVERRIDE_ADAPTER = SimpleOverrideAdapter()


def materialize_simple_override_runtime(
    output_directory: str,
    geometry_records: list[dict] | None = None,
    texture_mark_payload: dict | None = None,
    toggle_draw_sets: list[dict] | None = None,
) -> dict:
    return DEFAULT_SIMPLE_OVERRIDE_ADAPTER.materialize(
        output_directory,
        geometry_records,
        texture_mark_payload,
        toggle_draw_sets,
    )


def build_simple_override_ini_content(runtime_plan: dict) -> str:
    return DEFAULT_SIMPLE_OVERRIDE_ADAPTER.build_ini_content(runtime_plan)


def write_simple_override_ini_from_runtime(
    output_directory: str,
    runtime_plan: dict,
    *,
    ini_file_name: str | None = None,
) -> str:
    return DEFAULT_SIMPLE_OVERRIDE_ADAPTER.write_ini(
        output_directory,
        runtime_plan,
        ini_file_name=ini_file_name,
    )


def _simple_texture_override_sections(runtime_plan: dict) -> list[str]:
    geometry_by_key = runtime_ini._geometry_records_by_key(list(runtime_plan.get("geometry", []) or []))
    if not geometry_by_key:
        return []
    lines: list[str] = [
        "; -------------------------------------------------",
        "; Simple TextureOverrides",
        "; -------------------------------------------------",
    ]
    for key in sorted(geometry_by_key):
        ib_hash, match_first_index, match_index_count = key
        suffix = runtime_ini._safe_suffix(f"{ib_hash}_{match_index_count}_{match_first_index}")
        lines.extend(
            [
                f"[TextureOverride_BMCSimple_{suffix}]",
                f"hash = {ib_hash}",
                f"match_index_count = {match_index_count}",
                "if vs == 201 || vs == 202 || vs == 203",
                "  handling = skip",
            ]
        )
        for record in geometry_by_key[key]:
            lines.extend(_simple_replay_part_lines(record, indent="  "))
        lines.extend(["endif", ""])
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _simple_replay_part_lines(record: dict, *, indent: str) -> list[str]:
    suffix = str(record.get("resource_suffix", "") or "")
    lines = [
        f"{indent}; replay {suffix}",
        f"{indent}ib = {record.get('index_resource_name')}",
    ]
    vertex_buffers = dict(record.get("vertex_buffers", {}) or {})
    for slot_name, vertex_buffer in sorted(vertex_buffers.items(), key=lambda item: runtime_ini._slot_sort_key(item[0])):
        lines.append(f"{indent}{slot_name} = {dict(vertex_buffer).get('resource_name')}")
    vb0 = vertex_buffers.get("vb0")
    if vb0 and "vb3" not in vertex_buffers:
        lines.append(f"{indent}vb3 = {dict(vb0).get('resource_name')}")
    draw_ranges = runtime_ini._draw_ranges_for_record(record)
    index = 0
    while index < len(draw_ranges):
        draw = draw_ranges[index]
        condition = runtime_ini._draw_toggle_condition(draw)
        if condition:
            lines.append(f"{indent}if {condition}")
            while index < len(draw_ranges) and runtime_ini._draw_toggle_condition(draw_ranges[index]) == condition:
                lines.extend(runtime_ini._drawindexed_lines(draw_ranges[index], record, indent=f"{indent}  "))
                index += 1
            lines.append(f"{indent}endif")
            continue
        lines.extend(runtime_ini._drawindexed_lines(draw, record, indent=indent))
        index += 1
    return lines
